name: Build Kernel

on:
  push:
    branches:
      - resukisu-susfs-kpm
  workflow_dispatch:
    inputs:
      kernel_branch:
        description: "Kernel branch to build"
        required: true
        default: "susfs"
      kernel_config:
        description: "Kernel config to build"
        required: false
        default: "mt6893_defconfig"

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.kernel_branch || github.ref_name }}
          submodules: recursive
          path: kernel_workspace
      
      - name: Patch KSU version base
        run: |
          sed -i 's/30000 + $(KSU_LOCAL_VERSION) + 700/35000 + $(KSU_LOCAL_VERSION) + 700/' \
          kernel_workspace/KernelSU/kernel/Kbuild
    
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ccache lld

      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        env:
          LLVM: 1
          LLVM_IAS: 1
        with:
          kernel-url: kernel_workspace/
          kernel-branch: ${{ github.event.inputs.kernel_branch || github.ref_name }}
          ccache: true
          config: ${{ github.event.inputs.kernel_config || 'mt6893_defconfig' }}
          arch: arm64
          aosp-gcc: false
          aosp-clang: false
          other-clang-url: https://github.com/kdrag0n/proton-clang.git
          other-clang-branch: master
          other-gcc32-url: https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9
          other-gcc32-branch: lineage-19.1
          other-gcc64-url: https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9
          other-gcc64-branch: lineage-19.1
          ksu: false
          ksu-other: false
          disable-lto: true
          anykernel3: true
          anykernel3-url: https://github.com/liwhy1/AnyKernel3
          access-token: ${{ secrets.GITHUB_TOKEN }}
          release: true
          extra-make-args: '[ 
            "CC=clang",
            "CONFIG_NO_ERROR_ON_MISMATCH=y",
            "CLANG_TRIPLE=aarch64-linux-gnu-"
          ]'
